name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xfvb:
        image: ubuntu:20.04
        options: --privileged
        ports:
          - 6000:6000
        runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install Android SDK
      run: sudo apt-get install -y openjdk-11-jdk && sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;21.3.6528147" "cmdline-tools;latest"

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release -t:Run -f net7.0-android

    - name: Publish APK
      run: dotnet publish -f net7.0-android -c Release -o ./output

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./output/**/*.apk
