name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;21.3.6528147" "cmdline-tools;latest"

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release -t:Run -f net8.0-android

    - name: Publish APK
      run: dotnet publish -f net8.0-android -c Release -o ./output

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./output/**/*.apk
